### ISSUE TITLE
NPE in project/package tree (Eclipse Neon RC2)

### ISSUE THREAD

**Issue by zingmane** [ystrot/glance#36]
I get a NullPointerException if glance search textbox is active/shown an then click on a tree node e.g. package/project explorer. Configuration dialog also seems to be broken. 
![glance_config](https://cloud.githubusercontent.com/assets/148202/16070425/8d226e74-32d5-11e6-936a-20d87cb99443.png)

Glance is really one of the most importent plugins to me!

Eclipse Java EE IDE for Web Developers.
Version: Neon Release Candidate 2 (4.6.0RC2)
Build id: 20160526-1324

`!ENTRY org.eclipse.ui 4 0 2016-06-10 14:31:21.803
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
    at com.xored.glance.ui.sources.ColorManager.getStore(ColorManager.java:50)
    at com.xored.glance.ui.sources.ColorManager.<init>(ColorManager.java:43)
    at com.xored.glance.ui.sources.ColorManager.getInstance(ColorManager.java:55)
    at com.xored.glance.ui.controls.decor.StructDecorator.erase(StructDecorator.java:140)
    at com.xored.glance.ui.controls.decor.StructDecorator.handleEvent(StructDecorator.java:71)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4415)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
    at org.eclipse.swt.widgets.Tree.CDDS_ITEMPREPAINT(Tree.java:1058)
    at org.eclipse.swt.widgets.Tree.wmNotifyChild(Tree.java:7541)
    at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5797)
    at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:2033)
    at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5351)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:4827)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5120)
    at org.eclipse.swt.internal.win32.OS.CallWindowProcW(Native Method)
    at org.eclipse.swt.internal.win32.OS.CallWindowProc(OS.java:2446)
    at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1552)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:4869)
    at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6074)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5107)
    at org.eclipse.swt.internal.win32.OS.CallWindowProcW(Native Method)
    at org.eclipse.swt.internal.win32.OS.CallWindowProc(OS.java:2446)
    at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1552)
    at org.eclipse.swt.widgets.Tree.WM_LBUTTONDOWN(Tree.java:6559)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:4807)
    at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6074)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:5107)
    at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
    at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2552)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3819)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1119)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1020)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)`

**Comment by szotsaki** [comment]
Seems to be fixed in a fork (for me). See here: https://github.com/ystrot/glance/issues/34#issuecomment-221998394

**Comment by c410-f3r** [comment]
Temporary workaround: Windows -> Preferences -> Keys, search for "Find Text in File" and bind with Glance's hotkey (Ctrl + Alt + F).

**Comment by evan4096** [comment]
Is there an alternative to glance in addition to the ootb eclipse "Find Text in File"?

**Comment by asalnik** [comment]
Fixed in 1.2.1.
