### ISSUE TITLE
glance cause neon 2 to hang if It is open and I click on project explorer

### ISSUE THREAD

**Issue by AEDWIP** [ystrot/glance#39]
I have been using glance for a while. **I love it!** I recently upgrade to neon if I have glance open in a text editor and they try to use glance on the project explore or just select a file in the project explore eclipse hangs. I am using a Mac and I need to force quit eclipse. Attached is a complete eclipse log file

  Glance Core	1.2.0.201609300916	com.xored.glance.feature.group	xored software, Inc.

!SESSION 2017-01-22 10:35:23.453 -----------------------------------------------
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_66
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/ad/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -keyring /Users/ad/.ecli
pse_keyring

This is a continuation of log file /Users/ad/workSpace/sc
[eclipse_glance_crash_log.txt](https://github.com/ystrot/glance/files/730967/eclipse_glance_crash_log.txt)
/.metadata/.bak_0.log
Created Time: 2017-01-22 10:55:57.352

!ENTRY org.eclipse.ui 4 0 2017-01-22 10:55:57.352
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
        at com.xored.glance.ui.sources.ColorManager.getStore(ColorManager.java:50)
        at com.xored.glance.ui.sources.ColorManager.<init>(ColorManager.java:43)
        at com.xored.glance.ui.sources.ColorManager.getInstance(ColorManager.java:55)
        at com.xored.glance.ui.utils.TextUtils.applyStyles(TextUtils.java:53)
        at com.xored.glance.ui.controls.text.styled.ListeningStyledTextSource.applyTextPresentation(ListeningStyledTextSource.java:92)
        at com.xored.glance.ui.controls.text.styled.ListeningStyledTextSource.lineGetStyle(ListeningStyledTextSource.java:81)
        at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:49)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)

**Comment by asalnik** [comment]
Fixed in 1.2.1.
